runtime: nodejs8
# [START gae_flex_postgres_env]
# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  SQL_USER: postgre
  SQL_PASSWORD: connect
  SQL_DATABASE: games
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: priceofgames:us-west1:gamesdb

beta_settings:
  cloud_sql_instances: priceofgames:us-west1:gamesdb
